### ISSUE TITLE
How about the performance tuning?

### ISSUE THREAD

**Issue by alexwenbj** [hhxsv5/php-sse#11]
If there are ten or more client connect to the event script, the server slow down very much, how to tune the performance?Thank you.

**Comment by hhxsv5** [comment]
To be honest, the performance of SSE in PHP-FPM mode is not good, because each request will occupy a worker process. If you have high requirements for performance, I suggest you use an asynchronous Http server to implement WebSocket, such as Swoole.

**Comment by alexwenbj** [comment]
Got it ,thank you.

**Comment by hhxsv5** [comment]
Welcome.
