### ISSUE TITLE
Push events only when POST method kicks in

### ISSUE THREAD

**Issue by ljfreelancer88** [hhxsv5/php-sse#14]
Sorry, I have a lot of questions regarding implementing Swoole, because their documentation is not that detailed enough for newbie. Anyway, Is it possible to push the events when there's a POST method only? See pseudo code below.
```
if request method is POST
  Push the updated/new event 
else
  Sleep momentarily or send a SSE comment to make the connection alive 
```
 Thank you again. You are a big help.

**Comment by hhxsv5** [comment]
See Swoole\Http\Request->server.
```php
if ($request->server['request_method'] === 'POST') {      
}
```

Indeed, [English documentation](https://www.swoole.co.uk/docs/modules/swoole-http-request-server) is not detailed enough. 
Sometimes Google translates [Chinese documentation](https://wiki.swoole.com/#/http_server?id=server) as another way.

**Comment by ljfreelancer88** [comment]
Hi, I've tried the following code below but seems not working. It doesn't push event when I use the Curl POST. On my Curl POST, it returns the SSE comment  `: no update`.
```
go(function() use ($request, $response) {
        (new SSESwoole($request, $response))->start(new Update(function () {
            if (isset($request->server['request_method']) && 
                $request->server['request_method'] === 'POST') {
                $time = date('Y-m-d H:i:s');
                $news = [['id' => $time, 'title' => 'title ' . $time, 'content' => 'content ' . $time]]; // Get news from database or service.
                return json_encode(['news' => $news]);
            }
                return false; // Return false if no new messages
        }, 2), 'news');
    });
```

**Comment by hhxsv5** [comment]
1.Start Swoole Http Server `php sse-swoole.php`.
![image](https://user-images.githubusercontent.com/7278743/84887539-76b8ed00-b0c8-11ea-9d54-c15b2548bd7e.png)
2.Run `curl -XPOST -N http://127.0.0.1:5200/`.
![image](https://user-images.githubusercontent.com/7278743/84887380-3a858c80-b0c8-11ea-81df-8b635884b432.png)

**Comment by ljfreelancer88** [comment]
Ow! the variable `$request` inside `if` statement is undefined, that's why it's not working. Here is the minor changes on the code `new Update(function() use ($request))`. Now it's working! Thank you so much for your help. Appreciate it.

Here is the final code for reference.
go(function() use ($request, $response) {
    (new SSESwoole($request, $response))->start(new Update(function() use ($request) {
        if ($request->server['request_method'] === 'POST') {
                $time = date('Y-m-d H:i:s');
                $news = [['id' => $time, 'title' => 'title ' . $time, 'content' => 'content ' . $time]]; // Get news from database or service.
                return json_encode(['news' => $news]);
            }
            return false;
    }, 2), 'news');
});
