### ISSUE TITLE
EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.

### ISSUE THREAD

**Issue by dev-afzy** [hhxsv5/php-sse#15]
Hi, 
I am getting proper response from when I call the specific route.
for example server.php is routed to 'http://127.0.0.1:8000/server' i am getting proper response as you said(but  Eventstream still empty this was another issue I found this package). But when i tried to trigger the  EventSource in my html file I am getting below error. From where the extra header is coming.

`EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.`

Please fix this issue. 
Thank you

**Comment by hhxsv5** [comment]
Please make sure these headers are set.
```php
header('Content-Type: text/event-stream');
header('Cache-Control: no-cache');
header('Connection: keep-alive');
header('X-Accel-Buffering: no');
```
