### ISSUE TITLE
StopSSEException() implementation

### ISSUE THREAD

**Issue by ljfreelancer88** [hhxsv5/php-sse#20]
Hi, sorry for this noob question. When this `$shouldStop` variable be `true`? :) I'm trying to implement this condition taken from your sample demo but I don't fully get. BTW, I'm currently using your package in Swoole. Thanks again.

```PHP
$shouldStop = false;
if ($shouldStop) {
    throw new StopSSEException();
}
```

**Comment by hhxsv5** [comment]
$shouldStop is used to disconnect the current SSE connection.
Such as the following example:
- Not logged in
- Illegal input parameter
