### ISSUE TITLE
Swoole Demo outdated?

### ISSUE THREAD

**Issue by FelixMittermeier** [hhxsv5/php-sse#21]
Is the example script showcasing the functionality with Swoole still valid? Tried it the whole day without success. I installed Swoole but the example script (https://github.com/hhxsv5/php-sse/blob/master/examples/sse-swoole.php) always throws an Uncaught Error: "Class Swoole\Http\Server not found".

Do you know if something changed and I just overlooked it etc.?

Any help would be much appreciated.

**Comment by hhxsv5** [comment]
Maybe you forgot to enable swoole extension in php.ini, use `php --ri swoole` to confirm whether swoole is enabled.

**Comment by FelixMittermeier** [comment]
Yeah, it is enabled. Both

`/opt/plesk/php/8.0/bin/php -m | grep swoole`
`swoole`

and

`php -m | grep swoole`
`swoole`

are showing the correct output but unfortunately I am still not able to use the extension in my php scripts. When using https://github.com/hhxsv5/php-sse/blob/master/examples/sse-swoole.php for testing purposes I am still getting an error
`Class "Swoole\Http\Server" not found`.

Everything has been restarted multiple times so this shouldn't be an issue.

**Comment by hhxsv5** [comment]
Whether different versions of php are installed, try to run `sse-swoole.php` with the php absolute path.
`/opt/plesk/php/8.0/bin/php sse-swoole.php`
And show me the output about `php --ri swoole` please.
Similar issue [#3246](https://github.com/swoole/swoole-src/issues/3246)

**Comment by FelixMittermeier** [comment]
Okay, so `/opt/plesk/php/8.0/bin/php --ri swoole`
outputs:
`
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.9
Built => Dec 23 2020 13:24:33
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
`
Directly running ssw-swoole.php leads to same error as described above.

Don't know if it is relevant in this context but I also asked the swoole maintainers at their GitHub page and they wrote it cannot be run in cli mode. But what's the point when execution by a user from a browser ist not possible? Your example looks like it is possible so I am a bit confused right now.
Link to the mentioned comment: https://github.com/swoole/swoole-src/issues/3952#issuecomment-750646304

**Comment by hhxsv5** [comment]
Yes, the Swoole example can only be run in cli mode, not in FPM.
Swoole has a built-in Http server, which is started in `cli` mode, and you should directly access http://127.0.0.1:5200/ in browser. not http://127.0.0.1/sse-swoole.php.

**Comment by FelixMittermeier** [comment]
Yeah that finally makes sense and would maybe explain the described behavior. I am going to try it out today or the next days.
Thank you very much for your help ☺️

**Comment by hhxsv5** [comment]
Anytime.

**Comment by FelixMittermeier** [comment]
For another reason I cannot test it right now unfortunately. But as said before I really think the way you described works out.
Closing the issue now because the former question has been answered. ☺️
